# https://github.com/patricorgi/dotfiles/blob/main/.config/kitty/kitty.conf
# mark1_foreground #74C7EC
# mark1_background #1E1E2E
# mark2_foreground #F9E2AF
# mark2_background #1E1E2E
# mark3_foreground #F38BA8
# mark3_background #1E1E2E

toggle_marker regex 1 \\bINFO\\b 2 \\bWARNING\\b 3 \\bERROR\\b 3 \\bFATAL\\b
map ctrl+shift+m toggle_marker regex 1 \\bINFO\\b 2 \\bWARNING\\b 3 \\bERROR\\b 3 \\bFATAL\\b