# ============================================================================ #
# region Kitty Theme
# ============================================================================ #
include themes/catppuccin-mocha.conf
# endregion


# ============================================================================ #
# region Fonts
# ============================================================================ #
include fonts/maple.conf
font_size 15.0
# endregion


# ============================================================================ #
# region Text cursor customization
# ============================================================================ #
cursor_trail 1
# endregion


# ============================================================================ #
# region Window layout
# ============================================================================ #
remember_window_size no
initial_window_width 110c
initial_window_height 30c

window_padding_width 12
placement_strategy top

hide_window_decorations titlebar-only

confirm_os_window_close 0
# endregion


# ============================================================================ #
# region Tab
# ============================================================================ #
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style round
# endregion


# ============================================================================ #
# region Color scheme
# ============================================================================ #
background_opacity 0.76
background_blur 30
# endregion


# ============================================================================ #
# region Advanced
# ============================================================================ #
# term xterm-256color
# endregion


# ============================================================================ #
# region OS specific tweaks
# ============================================================================ #
# OS specific tweaks
macos_titlebar_color background
macos_quit_when_last_window_closed yes
macos_traditional_fullscreen yes
macos_option_as_alt yes
# endregion


# ============================================================================ #
# region Remote control
# ============================================================================ #
allow_remote_control yes
listen_on unix:/tmp/kitty
# endregion


# ============================================================================ #
# region Separated configurations
# ============================================================================ #
include mappings.conf # Mappings
include marker.conf # Marker
# endregion
