[tools]
bun = "latest"
deno = "latest"
go = "latest"
java = "temurin-21"
node = "lts"
"npm:@antfu/ni" = "latest"
python = "latest"
"npm:prettier" = "latest"
"npm:whistle" = "latest"
"npm:@rizumu/nai" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
