[preview]
max_width = 1200
max_height = 1000

[opener]
edit = [
	{ run = "${EDITOR:-vi} %s", desc = "$EDITOR", for = "unix", block = true },
	{ run = "cursor %s", desc = "cursor", for = "unix", orphan = true },
	{ run = "code %s", desc = "code", for = "unix", orphan = true },
	{ run = "code -w %s", desc = "code (block)", for = "unix", block = true },
]
glow = [
	{ run = "glow --tui %s", block = true, for = "unix" },
]

[open]
prepend_rules = [
	{ url = "*.md", use = "glow" },
]

[[plugin.prepend_fetchers]]
id  = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id  = "git"
url = "*/"
run = "git"